### PR TITLE
Add more new shortener ports and more search engines

### PR DESCRIPTION
**Pull request by iNanmu**
Add more new shortener ports (Current: 13)

### CODE REVIEW

**Review by NiklasEi — COMMENTED** [review]
I believe there was some mixup of classes. One of your commits copy-pastes the command class to the language class. 
As far as I can see the only commits with content are in config.yml and Shortener.java. Could you remove the others please?
Thank you for the PR! Support for more then one shortener service is a great feature. I'll add you to the SpigotMC page as a Contributer. Do you have an Account on Spigot?

**Comment by NiklasEi** [comment]
You are new to Git and GitHub, could that be? :s
If you delete a file and then commit that change, it won't delete the changes in the file, but it will really delete the file from the repository.
In my opinion the easiest thing for you to do now would be to get a clean fork of LMGTFY and copy only your config.yml and your shortener class to the clean version. Then create a new PR.

Or just leave it this way and I will cherry-pick the two commits after my exams (in 4 days). Thanks :smile:

**Comment by iNanmu** [comment]
Sorry, I am a Chinese, English is not very good at ...

Other Java and YML have been removed.
Sorry, I used this website for the first time. :)

My faucet username is Canmenglo

**Comment by Zhb1508444061** [comment]
My faucet username is CanMengLo

**Comment by Zhb1508444061** [comment]
@NiklasEi
OK, I wish you a smooth exam. 
Because we have now is 1:00 more. 
So I should go to bed.

**Comment by Zhb1508444061** [comment]
Custom Search Engine has been submitted ...  :) 

If you understand Chinese just fine ...  :)

**Comment by iNanmu** [comment]
Custom Search Engine has been submitted ...

If you understand Chinese just fine ...

**Pull request closed without merging**
